name: Build Release Binaries

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Linux AMD64
        run: |
          GOOS=linux GOARCH=amd64 go build -o aicmd-linux-amd64 main.go ollama_client.go

      - name: Build Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -o aicmd-linux-arm64 main.go ollama_client.go

      - name: Build macOS ARM64 (Apple Silicon)
        run: |
          GOOS=darwin GOARCH=arm64 go build -o aicmd-darwin-arm64 main.go ollama_client.go
  
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
                aicmd-linux-amd64
                aicmd-linux-arm64
                aicmd-darwin-arm64
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
